# Generated by Django 5.1.1 on 2024-12-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_searchlog_created_at_searchlog_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='timestamp',
        ),
    ]
