# Generated by Django 5.1.1 on 2024-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_rename_timestamp_searchlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
